# Pentagon numbers
# Myyura

# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first 
# ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
# difference are pentagonal and D = |Pk − Pj| is minimised; what is the 
# value of D?

# x = Pn = n(3n - 1)/2
# ->  0 = 3n^2 -n -2x
# ->  n = (1 + sqrt(1 + 24x)) / 6

import sys
import math

def P(n):
    return n * (3 * n - 1) // 2

def is_pentagon(n):
    r = math.sqrt(1 + 24 * n)
    return r % 6 == 5

def min_pentagon_numbers():
    minimum = sys.maxsize
    for i in range(1, 5001):
        for j in range(i + 1, 5001):
            if is_pentagon(P(j) - P(i)) and is_pentagon(P(i) + P(j)):
                minimum = min(P(j) - P(i), minimum)

    return minimum
            
print(min_pentagon_numbers())