# Triangular, pentagonal, and hexagonal
# Myyura

# Triangle, pentagonal, and hexagonal numbers are generated by the following 
# formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

# Tn = n(n + 1)/2 = (2n - 1)((2n - 1) + 1) / 2
#    = m(2m - 1)
# a triangle is a hexagonal

import math
import itertools

def is_pentagon(n):
    r = math.sqrt(1 + 24 * n)
    return r % 6 == 5

def triangle_pentagonal_hexagonal(start):
    for i in itertools.count(start):
        hexagonal = i * (2 * i - 1)
        if (is_pentagon(hexagonal)):
            return hexagonal
    return -1
            
print(triangle_pentagonal_hexagonal(144))